# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../gui/add_family.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddFamily(object):
    def setupUi(self, AddFamily):
        AddFamily.setObjectName("AddFamily")
        AddFamily.resize(517, 433)
        self.centralWidget = QtWidgets.QWidget(AddFamily)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_fam_name = QtWidgets.QLabel(self.frame_2)
        self.lbl_fam_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_fam_name.setObjectName("lbl_fam_name")
        self.horizontalLayout_2.addWidget(self.lbl_fam_name)
        self.tb_fam_name = QtWidgets.QLineEdit(self.frame_2)
        self.tb_fam_name.setObjectName("tb_fam_name")
        self.horizontalLayout_2.addWidget(self.tb_fam_name)
        self.btn_search = QtWidgets.QPushButton(self.frame_2)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_2.addWidget(self.btn_search)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lv_search_result = QtWidgets.QListWidget(self.groupBox)
        self.lv_search_result.setObjectName("lv_search_result")
        self.horizontalLayout_3.addWidget(self.lv_search_result)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lv_be_added_family = QtWidgets.QListWidget(self.groupBox_2)
        self.lv_be_added_family.setObjectName("lv_be_added_family")
        self.horizontalLayout_4.addWidget(self.lv_be_added_family)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_add = QtWidgets.QPushButton(self.frame_3)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_cancel = QtWidgets.QPushButton(self.frame_3)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        AddFamily.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(AddFamily)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 517, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        AddFamily.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(AddFamily)
        QtCore.QMetaObject.connectSlotsByName(AddFamily)

    def retranslateUi(self, AddFamily):
        _translate = QtCore.QCoreApplication.translate
        AddFamily.setWindowTitle(_translate("AddFamily", "Family"))
        self.lbl_fam_name.setText(_translate("AddFamily", "Name of Family Member"))
        self.btn_search.setText(_translate("AddFamily", "Search"))
        self.groupBox.setTitle(_translate("AddFamily", "Search Result"))
        self.groupBox_2.setTitle(_translate("AddFamily", "Be added to Family"))
        self.btn_add.setText(_translate("AddFamily", "Add"))
        self.btn_cancel.setText(_translate("AddFamily", "Cancel"))
        self.menuMenu.setTitle(_translate("AddFamily", "Menu"))

