# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../gui/view_member.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ViewMember(object):
    def setupUi(self, ViewMember):
        ViewMember.setObjectName("ViewMember")
        ViewMember.resize(599, 826)
        self.centralWidget = QtWidgets.QWidget(ViewMember)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_email = QtWidgets.QLabel(self.groupBox)
        self.lbl_email.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_email.setObjectName("lbl_email")
        self.gridLayout.addWidget(self.lbl_email, 3, 0, 1, 1)
        self.lbl_phone = QtWidgets.QLabel(self.groupBox)
        self.lbl_phone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_phone.setObjectName("lbl_phone")
        self.gridLayout.addWidget(self.lbl_phone, 4, 0, 1, 1)
        self.tb_kor_name = QtWidgets.QLineEdit(self.groupBox)
        self.tb_kor_name.setReadOnly(True)
        self.tb_kor_name.setObjectName("tb_kor_name")
        self.gridLayout.addWidget(self.tb_kor_name, 0, 1, 1, 1)
        self.tb_email = QtWidgets.QLineEdit(self.groupBox)
        self.tb_email.setReadOnly(True)
        self.tb_email.setObjectName("tb_email")
        self.gridLayout.addWidget(self.tb_email, 3, 1, 1, 1)
        self.de_dob = QtWidgets.QDateEdit(self.groupBox)
        self.de_dob.setReadOnly(True)
        self.de_dob.setCalendarPopup(False)
        self.de_dob.setObjectName("de_dob")
        self.gridLayout.addWidget(self.de_dob, 5, 1, 1, 1)
        self.lbl_kor_name = QtWidgets.QLabel(self.groupBox)
        self.lbl_kor_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_kor_name.setObjectName("lbl_kor_name")
        self.gridLayout.addWidget(self.lbl_kor_name, 0, 0, 1, 1)
        self.lbl_eng_name = QtWidgets.QLabel(self.groupBox)
        self.lbl_eng_name.setObjectName("lbl_eng_name")
        self.gridLayout.addWidget(self.lbl_eng_name, 2, 0, 1, 1)
        self.tb_phone = QtWidgets.QLineEdit(self.groupBox)
        self.tb_phone.setReadOnly(True)
        self.tb_phone.setObjectName("tb_phone")
        self.gridLayout.addWidget(self.tb_phone, 4, 1, 1, 1)
        self.tb_eng_name = QtWidgets.QLineEdit(self.groupBox)
        self.tb_eng_name.setReadOnly(True)
        self.tb_eng_name.setObjectName("tb_eng_name")
        self.gridLayout.addWidget(self.tb_eng_name, 2, 1, 1, 1)
        self.lbl_birthday = QtWidgets.QLabel(self.groupBox)
        self.lbl_birthday.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_birthday.setObjectName("lbl_birthday")
        self.gridLayout.addWidget(self.lbl_birthday, 5, 0, 1, 1)
        self.lbl_gender = QtWidgets.QLabel(self.groupBox)
        self.lbl_gender.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_gender.setObjectName("lbl_gender")
        self.gridLayout.addWidget(self.lbl_gender, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.groupBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_gender_male = QtWidgets.QRadioButton(self.frame_3)
        self.rb_gender_male.setCheckable(True)
        self.rb_gender_male.setObjectName("rb_gender_male")
        self.horizontalLayout.addWidget(self.rb_gender_male)
        self.rb_gender_female = QtWidgets.QRadioButton(self.frame_3)
        self.rb_gender_female.setCheckable(True)
        self.rb_gender_female.setObjectName("rb_gender_female")
        self.horizontalLayout.addWidget(self.rb_gender_female)
        self.gridLayout.addWidget(self.frame_3, 7, 1, 1, 1)
        self.lbl_pic_view = QtWidgets.QLabel(self.groupBox)
        self.lbl_pic_view.setText("")
        self.lbl_pic_view.setObjectName("lbl_pic_view")
        self.gridLayout.addWidget(self.lbl_pic_view, 0, 2, 6, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.tb_address = QtWidgets.QLineEdit(self.groupBox)
        self.tb_address.setReadOnly(True)
        self.tb_address.setObjectName("tb_address")
        self.gridLayout.addWidget(self.tb_address, 6, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cb_duty = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_duty.setEnabled(True)
        self.cb_duty.setEditable(False)
        self.cb_duty.setObjectName("cb_duty")
        self.gridLayout_2.addWidget(self.cb_duty, 4, 1, 1, 1)
        self.lbl_duty = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_duty.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_duty.setObjectName("lbl_duty")
        self.gridLayout_2.addWidget(self.lbl_duty, 4, 0, 1, 1)
        self.tb_baptism_place = QtWidgets.QLineEdit(self.groupBox_2)
        self.tb_baptism_place.setReadOnly(True)
        self.tb_baptism_place.setObjectName("tb_baptism_place")
        self.gridLayout_2.addWidget(self.tb_baptism_place, 2, 1, 1, 1)
        self.lbl_baptism_date = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_baptism_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_baptism_date.setObjectName("lbl_baptism_date")
        self.gridLayout_2.addWidget(self.lbl_baptism_date, 1, 0, 1, 1)
        self.btn_show_bible_study = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_show_bible_study.setObjectName("btn_show_bible_study")
        self.gridLayout_2.addWidget(self.btn_show_bible_study, 9, 1, 1, 1)
        self.lbl_new_family_study = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_new_family_study.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_new_family_study.setObjectName("lbl_new_family_study")
        self.gridLayout_2.addWidget(self.lbl_new_family_study, 8, 0, 1, 1)
        self.de_reg = QtWidgets.QDateEdit(self.groupBox_2)
        self.de_reg.setReadOnly(True)
        self.de_reg.setCalendarPopup(False)
        self.de_reg.setObjectName("de_reg")
        self.gridLayout_2.addWidget(self.de_reg, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 9, 0, 1, 1)
        self.chk_new_comer_study = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_new_comer_study.setCheckable(True)
        self.chk_new_comer_study.setObjectName("chk_new_comer_study")
        self.gridLayout_2.addWidget(self.chk_new_comer_study, 7, 1, 1, 1)
        self.tb_baptism_by = QtWidgets.QLineEdit(self.groupBox_2)
        self.tb_baptism_by.setEnabled(True)
        self.tb_baptism_by.setReadOnly(True)
        self.tb_baptism_by.setObjectName("tb_baptism_by")
        self.gridLayout_2.addWidget(self.tb_baptism_by, 3, 1, 1, 1)
        self.lbl_register_date = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_register_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_register_date.setObjectName("lbl_register_date")
        self.gridLayout_2.addWidget(self.lbl_register_date, 0, 0, 1, 1)
        self.chk_new_family_study = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_new_family_study.setEnabled(True)
        self.chk_new_family_study.setCheckable(True)
        self.chk_new_family_study.setChecked(False)
        self.chk_new_family_study.setObjectName("chk_new_family_study")
        self.gridLayout_2.addWidget(self.chk_new_family_study, 8, 1, 1, 1)
        self.cb_dept = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_dept.setObjectName("cb_dept")
        self.gridLayout_2.addWidget(self.cb_dept, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 1)
        self.de_bap = QtWidgets.QDateEdit(self.groupBox_2)
        self.de_bap.setReadOnly(True)
        self.de_bap.setCalendarPopup(False)
        self.de_bap.setObjectName("de_bap")
        self.gridLayout_2.addWidget(self.de_bap, 1, 1, 1, 1)
        self.lbl_new_comer_study = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_new_comer_study.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_new_comer_study.setObjectName("lbl_new_comer_study")
        self.gridLayout_2.addWidget(self.lbl_new_comer_study, 7, 0, 1, 1)
        self.lbl_baptism_by = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_baptism_by.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_baptism_by.setObjectName("lbl_baptism_by")
        self.gridLayout_2.addWidget(self.lbl_baptism_by, 3, 0, 1, 1)
        self.lbl_baptism_place = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_baptism_place.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_baptism_place.setObjectName("lbl_baptism_place")
        self.gridLayout_2.addWidget(self.lbl_baptism_place, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 6, 0, 1, 1)
        self.cb_group = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_group.setObjectName("cb_group")
        self.gridLayout_2.addWidget(self.cb_group, 6, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_show = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_show.setObjectName("btn_show")
        self.verticalLayout_3.addWidget(self.btn_show)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_cancel = QtWidgets.QPushButton(self.frame_2)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.btn_save = QtWidgets.QPushButton(self.frame_2)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        ViewMember.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(ViewMember)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 599, 22))
        self.menuBar.setDefaultUp(True)
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        ViewMember.setMenuBar(self.menuBar)
        self.actionfiles = QtWidgets.QAction(ViewMember)
        self.actionfiles.setObjectName("actionfiles")
        self.actionnew = QtWidgets.QAction(ViewMember)
        self.actionnew.setObjectName("actionnew")
        self.actionedit = QtWidgets.QAction(ViewMember)
        self.actionedit.setObjectName("actionedit")
        self.menuMenu.addAction(self.actionfiles)
        self.menuMenu.addAction(self.actionnew)
        self.menuMenu.addAction(self.actionedit)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(ViewMember)
        QtCore.QMetaObject.connectSlotsByName(ViewMember)

    def retranslateUi(self, ViewMember):
        _translate = QtCore.QCoreApplication.translate
        ViewMember.setWindowTitle(_translate("ViewMember", "Add New Member"))
        self.groupBox.setTitle(_translate("ViewMember", "Personal Information"))
        self.lbl_email.setText(_translate("ViewMember", "E-Mail"))
        self.lbl_phone.setText(_translate("ViewMember", " Phone"))
        self.de_dob.setDisplayFormat(_translate("ViewMember", "MM/dd/yyyy"))
        self.lbl_kor_name.setText(_translate("ViewMember", "Korean Name"))
        self.lbl_eng_name.setText(_translate("ViewMember", "English Name"))
        self.lbl_birthday.setText(_translate("ViewMember", "Date of Birth"))
        self.lbl_gender.setText(_translate("ViewMember", "Gender"))
        self.rb_gender_male.setText(_translate("ViewMember", "Male"))
        self.rb_gender_female.setText(_translate("ViewMember", "Female"))
        self.label.setText(_translate("ViewMember", "Address"))
        self.groupBox_2.setTitle(_translate("ViewMember", "Additional Information"))
        self.lbl_duty.setText(_translate("ViewMember", "Duty"))
        self.lbl_baptism_date.setText(_translate("ViewMember", "Baptism Date"))
        self.btn_show_bible_study.setText(_translate("ViewMember", "Show"))
        self.lbl_new_family_study.setText(_translate("ViewMember", "New Family Study"))
        self.de_reg.setDisplayFormat(_translate("ViewMember", "MM/dd/yyyy"))
        self.label_12.setText(_translate("ViewMember", "Bible Study"))
        self.chk_new_comer_study.setText(_translate("ViewMember", "Complete"))
        self.lbl_register_date.setText(_translate("ViewMember", "Registration Date"))
        self.chk_new_family_study.setText(_translate("ViewMember", "Complete"))
        self.label_2.setText(_translate("ViewMember", "Department"))
        self.de_bap.setDisplayFormat(_translate("ViewMember", "MM/dd/yyyy"))
        self.lbl_new_comer_study.setText(_translate("ViewMember", "Newcomer Study"))
        self.lbl_baptism_by.setText(_translate("ViewMember", "Baptizer"))
        self.lbl_baptism_place.setText(_translate("ViewMember", "Baptism Site"))
        self.label_3.setText(_translate("ViewMember", "Group"))
        self.groupBox_3.setTitle(_translate("ViewMember", "Family Infomation"))
        self.btn_show.setText(_translate("ViewMember", "Show"))
        self.btn_cancel.setText(_translate("ViewMember", "Cancel"))
        self.btn_save.setText(_translate("ViewMember", "Save"))
        self.menuMenu.setTitle(_translate("ViewMember", "Menu"))
        self.actionfiles.setText(_translate("ViewMember", "files"))
        self.actionnew.setText(_translate("ViewMember", "new"))
        self.actionedit.setText(_translate("ViewMember", "edit"))

